### ISSUE TITLE
Compiling with gsc into standalone interpreter

### ISSUE THREAD

**Issue by alexshendi** [imrehorvath/CS61A#1]
Hi,

I tried building a standalone logo interpreter with your code, but had to make some small changes to make it compile. I am using Gambit-C release 4.9.3.
Changes are in Logo.patch.txt , a short summary of changes is below:
* moved scheme macros to a separate file, macros.scm
* changed definition of define-class macro to: ```(define-macro (define-class form . rest)  `(make-definitions (quote ,(cons form rest))))```
* created new file mylogo.scm 
* change exit-logo procedure to call (exit 0)
* additionally check for EOF object in line-obj in logo.scm
* maybe-num is redefined in logo.scm, line 419. Rename that instance to logo-maybe-num. It isn't called anyway.
* To compile program; gsc -exe mylogo.scm

Let me know what you think.

[Logo.patch.txt](https://github.com/imrehorvath/CS61A/files/7723769/Logo.patch.txt)
[macros.scm.txt](https://github.com/imrehorvath/CS61A/files/7723770/macros.scm.txt)
[mylogo.scm.txt](https://github.com/imrehorvath/CS61A/files/7723771/mylogo.scm.txt)

**Comment by imrehorvath** [comment]
Hello @alexshendi !

Thanks for experimenting with this old project! As stated, it was a former programming project issued at UCB. This repository contains my solution to that programming project. Gambit scheme came into the picture only because of the need for a scheme interpreter which runs in the browser.  Fortunately, Marc Feeley has created one.

I don't know what your intention is, but you can use the official Berkeley Logo standalone executable, if you want to play with the Berkeley Logo dialect. This project was not meant to produce an efficient, production Logo interpreter. The goal was to learn how to write a Logo interpreter in a language which has a lot in common with Logo itself.

Some comments to your changes.

- The `exit-logo` is a continuation, which essentially drops you back to the place, from where you've called the `driver-loop` procedure. It is not meant to exit the scheme interpreter completely.
- The `logo-load` procedure deals with reading from files, including the `eof-object?`-check. The `line-obj` class is not meant to do that. It is meant to hold the "line" for parsing.
- The `maybe-num` procedure is called indirectly and is used by the arithmetic primitives.
- The rest you've changed like macro-definitions and some procedures are with the supplied code by UCB for the project.
